name: Node CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]

    env:
      BASE_REF: ${{ github.base_ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make git diff HEAD^ work
          fetch-depth: 2

      # # if we can ever figure out how to checkout just the 2 commits together, do that
      # - name: Checkout for PR
      #   # We use the actions/checkout token here, which got persisted
      #   run: git fetch origin $BASE_REF --depth=1

      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22, 24]

    env:
      BASE_REF: ${{ github.base_ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make git diff HEAD^ work
          fetch-depth: 2

      # # if we can ever figure out how to checkout just the 2 commits together, do that
      # - name: Checkout for PR
      #   # We use the actions/checkout token here, which got persisted
      #   run: git fetch origin $BASE_REF --depth=1

      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm test
        env:
          GH_EVENT: ${{ github.event_name }}
