name: Node CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    env:
      BASE_REF: ${{ github.base_ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make git diff HEAD^ work
          fetch-depth: 2

      # # if we can ever figure out how to checkout just the 2 commits together, do that
      # - name: Checkout for PR
      #   # We use the actions/checkout token here, which got persisted
      #   run: git fetch origin $BASE_REF --depth=1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    env:
      BASE_REF: ${{ github.base_ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make git diff HEAD^ work
          fetch-depth: 2

      # # if we can ever figure out how to checkout just the 2 commits together, do that
      # - name: Checkout for PR
      #   # We use the actions/checkout token here, which got persisted
      #   run: git fetch origin $BASE_REF --depth=1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm ci
      - run: npm test
        env:
          GH_EVENT: ${{ github.event_name }}
